# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  SKIP_CI_FILTER: 'skip ci'

steps:
- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'export PATH="/home/vsts/.local/bin:$PATH"'
    customCommand: 'run-script build'